### ISSUE TITLE
Failed start task

### ISSUE THREAD

**Issue by ovionlogis** [fenwik/togglinear#2]
Error: `postTogglTimeEntryStart` request failed
    at startTimeEntry (/usr/local/lib/node_modules/@fenwik/togglinear/src/startTimeEntry.js:26:11)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async seq (/usr/local/lib/node_modules/@fenwik/togglinear/src/index.js:37:28)

**Comment by dt-medicin** [comment]
There was a problem with deleted project in current user info request.
